language: python
python:
- '2.7'
- '3.5'
- '3.6'
matrix:
  include:
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
install:
- python setup.py install
- pip install coveralls
script:
- coverage run --source=darklyrics setup.py test
- coveralls
deploy:
  provider: pypi
  user: res0nance
  on:
    tags: true
    branch: master
    python: '3.6'
  password:
    secure: a0ZyREZcFQ9SzncUPcl43fATVMtPf4LQe39TlXfldPiYGooJkZpyRE+7lrNjjXr3SgH3mtUfwCZ0ai6arh+APWEyuAfhEDQwuggzrhihl+XAhGYmfwrth+tw/HOTza0om8XXHOYH8IBhR+x/TDJeuOi8q1IbBBFMIcTNe2yGbDFPNe43dJQCjynamb5wuE/eMrLwfyT6OVEZBXpUBVRY4XURv6pRXzxleVuDUJbYPZr3SYF63UbIF5f9MJtRHcVDg7CDlH3VQ35JhlNyVqf233JBeHNnYE1U2UkkTh1Kl4rDiQMxUkUVOI/ITzeNXCGYMcvMY8ly1m1cWmt5CzCEI34JAYwYZ/4c7OmFVvi1KDbjC8iKaqylaGO7RfiFaAkO3123MWAlIX64VluPvDyTqoQRc0mStWQAh6RyeQzyD3upK11JsG/3flwcM5L++Gk3c6pkydaIze6of0w/CrBfDLmRO6dATB6km3YOEFyAprQrvFEX5NZqxMXbDo9SyPi4sAGtwPzo0/Sx8Df7doOHtshB1bPoq1az/ui+SQ8CNcp6ybK9AkeiRLiyD/0vFQbHqjjUQyS1eAS6j7OhG2MvA6x+o2Qja6b0b5ru+ThZV/aN0IfUpiQnx5SFTnOKFtpsJbmBtf2ppTxwJeobaC7js0QgyCSICBUU88Kmf65OX10=
